

Public Class TipoDocXMLDTO
    Public Sub New(tipoDoc As TpDocXML, tagRaiz As String)
        Me.TipoDoc = tipoDoc
        Me.TagRaiz = tagRaiz
    End Sub

    Public Enum TpDocXML
        CTeOS = 1
        CTe = 2
        CTeGTVe = 3
        CTeLote = 4
        CTeRespostaLote = 5
        CTeConsultaSit = 6
        CTeInutilizacao = 7
        CTeConsultaStatus = 8
        CTeEvento = 9
        CTeConsultaDFe = 10
        CTeDistNSUAut = 11
        CTeDistSVD = 12
        CTeEventoEPEC = 13
        CTeEventoCartaCorrecao = 14
        CTeEventoCancelamento = 15
        CTeEventoRegistroMultimodal = 16
        CTeEventoCTeComplementar = 17
        CTeEventoCancCTeComplementar = 18
        CTeEventoMultimodal = 20
        CTeEventoRegistroPassagem = 21
        CTeEventoRegistroPassagemAuto = 22
        CTeEventoAutorizadoMDFe = 23
        CTeEventoCanceladoMDFe = 24
        CTeEventoSubstituido = 25
        CTeEventoPrestacaoDesacordo = 27
        CTeEventoCancPrestDesacordo = 28
        CTeEventoInsucessoEntrega = 29
        CTeEventoCancInsucessoEntrega = 30
        CTeEventoLiberaPrazoCancelamento = 31
        CTeEventoLiberaEPEC = 32
        CTeEventoComprovanteEntrega = 33
        CTeEventoCancComprovanteEntrega = 34
        CTeModalRodoviario = 35
        CTeModalAereo = 36
        CTeModalFerroviario = 37
        CTeModalAquaviario = 38
        CTeModalDutoviario = 39
        CTeModalMultimodal = 40
        CTeModalRodoviarioOS = 41
        CTeEventoGTVeAutorizadoCTeOS = 42
        CTeEventoGTVeCanceladoCTeOS = 43
        BPe = 44
        BPeTM = 45
        BPeConsultaSit = 46
        BPeConsultaStatus = 47
        BPeConsultaDFe = 48
        BPeEvento = 49
        BPeEventoCancelamento = 50
        BPeEventoSubstituicao = 51
        BPeEventoNaoEmbarque = 52
        BPeEventoAlteracaoPoltrona = 53
        BPeEventoLiberaPrazoCancelamento = 54
        BPeEventoExcessoBagagem = 55
        BPeDistribuicao = 56
        NF3e = 57
        NF3eLote = 58
        NF3eRespostaLote = 59
        NF3eConsultaSit = 60
        NF3eEvento = 61
        NF3eConsultaStatus = 62
        NF3eConsultaDFe = 63
        NF3eDistribuicao = 64
        NF3eEventoCancelamento = 65
        NF3eEventoSubstituicao = 66
        NF3eEventoLiberaPrazoCancelmento = 67
        MDFe = 68
        MDFeLote = 69
        MDFeRespostaLote = 70
        MDFeConsultaSit = 71
        MDFeConsultaDFe = 72
        MDFeConsultaStatus = 73
        MDFeConsultaNaoEncerrado = 74
        MDFeConsultaPlaca = 75
        MDFeDistribuicao = 76
        MDFeDistribuicaoAtores = 77
        MDFeDistribuicaoSVBA = 78
        MDFeEvento = 79
        MDFeEventoCancelamento = 80
        MDFeEventoEncerramento = 81
        MDFeEventoRegistroPassagem = 82
        MDFeEventoRegistroPassagemAuto = 83
        MDFeEventoLiberaPrazoCancelamento = 84
        MDFeEventoInclusaoCondutor = 85
        MDFeEventoInclusaoDFe = 86
        MDFeEventoEncerramentoFisco = 87
        MDFeEventoPgtoOper = 88
        MDFeEventoConfirmaOperacao = 89
        MDFeEventoAlteracaoPagtoOper = 90
        MDFeEventoRegistroOnusGravame = 91
        MDFeEventoCancRegistroOnusGravame = 92
        MDFeEventoPgtoTotalDE = 93
        MDFeEventoCancPgtoTotalDF = 94
        MDFeEventoBaixaAtivoFinanceiro = 95
        MDFeEventoCancBaixaAtivoFinanceiro = 96
        MDFeModalAereo = 97
        MDFeModalAquaviario = 98
        MDFeModalRodoviario = 99
        MDFeModalFerroviario = 100
        MDFeManCadTransp = 101
        MDFeManCadFrota = 102
        NFCOM = 103
        NFCOMConsultaSit = 104
        NFCOMConsultaDFe = 105
        NFCOMConsultaStatus = 106
        NFCOMDistribuicao = 107
        NFCOMEvento = 108
        NFCOMEventoCancelamento = 109
        NFCOMEventoLiberaPrazoCancelamento = 110
        NFCOMEventoSubstituicao = 111
        NFCOMEventoAjuste = 112
        NFCOMEventoCancelamemtoAjuste = 113
        NFCOMEventoCofaturamento = 114
        NFCOMEventoCancelamentoCofaturamento = 115
        NFCOMEventoSubstituidaCofaturamento = 116
    End Enum

    Public Property TipoDoc As TpDocXML
    Public Property TagRaiz As String

End Class
